'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase';

const subjects=['Mathematics','English Language','Physics','Chemistry','Biology','Economics','Government','Literature','Computer Science','Further Mathematics'];
const exams=['JAMB / UTME','WAEC / SSCE','NECO','IGCSE','A-Level','BECE'];
const empty={first_name:'',last_name:'',email:'',phone:'',city:'',bio:'',qualifications:'',subjects:[] as string[],exams:[] as string[],experience:'',formats:[] as string[],availability:'',tech:'',screening:''};
export default function Apply(){const [step,setStep]=useState(1);const [data,setData]=useState<any>(empty);const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [done,setDone]=useState('');
useEffect(()=>{const d=localStorage.getItem('pta-tutor-draft');if(d)try{setData(JSON.parse(d))}catch{}},[]);useEffect(()=>{localStorage.setItem('pta-tutor-draft',JSON.stringify(data))},[data]);
const pct=useMemo(()=>step*20,[step]);
function set(k:string,v:any){setData((d:any)=>({...d,[k]:v}))} function toggle(k:string,v:string){set(k,data[k].includes(v)?data[k].filter((x:string)=>x!==v):[...data[k],v])}
function next(){if(step===1&&!data.first_name.trim())return alert('Please enter your first name.');if(step===1&&!data.email.includes('@'))return alert('Please enter a valid email.');setStep(Math.min(5,step+1))}
async function submit(){setBusy(true);try{const sb=supabase();const {data:existing}=await sb.from('tutor_applications').select('id,reference_no').eq('email',data.email.trim().toLowerCase()).in('status',['new','reviewing','shortlisted','demo_scheduled']).limit(1);if(existing?.length)throw new Error(`An active application already exists (${existing[0].reference_no}).`);const payload={reference_no:'',email:data.email.trim().toLowerCase(),first_name:data.first_name,last_name:data.last_name,phone:data.phone,city:data.city,bio:data.bio,qualifications:data.qualifications.split('\n').filter(Boolean),subjects:data.subjects,exam_categories:data.exams,experience_years:Number(data.experience)||0,teaching_formats:data.formats,availability:{text:data.availability},technology:{text:data.tech},screening:{text:data.screening},status:'new'};const {data:app,error}=await sb.from('tutor_applications').insert(payload).select('reference_no').single();if(error)throw error;if(files.length&&app){for(const f of files.slice(0,5)){const path=`${app.reference_no}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('tutor-documents').upload(path,f,{upsert:false});if(up.error)console.warn(up.error);else await sb.from('tutor_applications').update({document_paths:[path]}).eq('reference_no',app.reference_no)}}localStorage.removeItem('pta-tutor-draft');setDone(app.reference_no)}catch(e:any){alert(e.message||'Could not submit application. Please try again.')}finally{setBusy(false)}}
if(done)return <main className="formPage"><div className="formShell"><div className="formCard" style={{textAlign:'center',padding:'60px 30px'}}><span className="eyebrow">APPLICATION RECEIVED</span><h1 style={{fontFamily:'Plus Jakarta Sans',fontSize:42}}>You're on your way.</h1><p className="sub">Your application reference number is</p><div style={{fontSize:30,fontWeight:800,margin:'18px 0',letterSpacing:1}}>{done}</div><p className="sub">Keep this reference number for your records. Our recruitment team will review your submission and contact you if you progress to the next stage.</p><Link className="btn primary" href="/">Return home</Link></div></div></main>;
return <main className="formPage"><div className="formShell"><div className="brand"><span className="mark">P</span><span>Pinnacle Tutors Academy</span></div><div className="formCard" style={{marginTop:25}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><span className="eyebrow">TUTOR APPLICATION</span><h1 style={{fontFamily:'Plus Jakarta Sans',marginBottom:0}}>Tell us about you</h1></div><b>Step {step} of 5</b></div><div className="progress"><div style={{width:`${pct}%`}}/></div>
{step===1&&<div className="fields"><div className="field"><label>First name *</label><input value={data.first_name} onChange={e=>set('first_name',e.target.value)}/></div><div className="field"><label>Last name *</label><input value={data.last_name} onChange={e=>set('last_name',e.target.value)}/></div><div className="field"><label>Email *</label><input type="email" value={data.email} onChange={e=>set('email',e.target.value)}/></div><div className="field"><label>Phone *</label><input value={data.phone} onChange={e=>set('phone',e.target.value)}/></div><div className="field full"><label>City / location</label><input value={data.city} onChange={e=>set('city',e.target.value)}/></div><div className="field full"><label>Short professional introduction</label><textarea rows={5} value={data.bio} onChange={e=>set('bio',e.target.value)}/></div></div>}
{step===2&&<><h3>What can you teach?</h3><p className="sub">Select every subject and exam category you are confident teaching.</p><div className="checkgrid">{subjects.map(x=><label className="check" key={x}><input type="checkbox" checked={data.subjects.includes(x)} onChange={()=>toggle('subjects',x)}/> {x}</label>)}</div><h3 style={{marginTop:28}}>Exam categories</h3><div className="checkgrid">{exams.map(x=><label className="check" key={x}><input type="checkbox" checked={data.exams.includes(x)} onChange={()=>toggle('exams',x)}/> {x}</label>)}</div></>}
{step===3&&<div className="fields"><div className="field full"><label>Qualifications (one per line)</label><textarea rows={6} placeholder="B.Sc. Mathematics\nPGDE\n..." value={data.qualifications} onChange={e=>set('qualifications',e.target.value)}/></div><div className="field"><label>Years of teaching experience</label><input type="number" min="0" value={data.experience} onChange={e=>set('experience',e.target.value)}/></div><div className="field"><label>Preferred formats</label><select multiple value={data.formats} onChange={e=>set('formats',Array.from(e.target.selectedOptions).map(o=>o.value))}><option>Online</option><option>In-person</option><option>Hybrid</option></select></div><div className="field full"><label>Relevant certificates / documents</label><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small style={{color:'#64748b'}}>Up to 5 files. Keep each file reasonably sized.</small></div></div>}
{step===4&&<div className="fields"><div className="field full"><label>When are you generally available?</label><textarea rows={6} placeholder="Weekdays 4pm–8pm; Saturday mornings..." value={data.availability} onChange={e=>set('availability',e.target.value)}/></div><div className="field full"><label>Technology &amp; internet readiness</label><textarea rows={5} placeholder="Describe your device, internet reliability and online teaching setup." value={data.tech} onChange={e=>set('tech',e.target.value)}/></div></div>}
{step===5&&<div className="fields"><div className="field full"><label>Screening question</label><textarea rows={8} placeholder="What makes an excellent tutor, and how do you help a struggling student improve?" value={data.screening} onChange={e=>set('screening',e.target.value)}/></div><div className="feature full"><b>Before you submit</b><p className="sub">We will securely store your application for recruitment review. Your information is not displayed to other applicants.</p></div></div>}
<div className="formActions">{step>1?<button className="btn ghost" onClick={()=>setStep(step-1)}>Back</button>:<Link className="btn ghost" href="/">Cancel</Link>}{step<5?<button className="btn primary" onClick={next}>Continue →</button>:<button className="btn primary" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit application'}</button>}</div></div></div></main>}
