import Link from 'next/link';

const benefits=[['01','Teach with purpose','Join a focused academic team committed to measurable student outcomes.'],['02','Flexible opportunities','Share your preferred subjects, levels, availability and teaching format.'],['03','Grow your career','Access a professional recruitment process and a platform built around great educators.']];
const steps=['Complete your profile','Tell us what you teach','Upload your credentials','Screening & demo'];
export default function Home(){return <>
<header className="hero"><div className="wrap nav"><div className="brand"><span className="mark">P</span><span>Pinnacle Tutors Academy</span></div><nav className="navlinks"><a href="#why">Why Pinnacle</a><a href="#process">Process</a><a href="#faq">FAQ</a></nav><Link className="btn primary" href="/apply">Apply to teach</Link></div>
<div className="wrap heroGrid"><div><span className="eyebrow">NOW RECRUITING EXCEPTIONAL TUTORS</span><h1>Teach brilliantly.<br/>Make an impact.</h1><p>Build the next generation of high-achieving students with Pinnacle Tutors Academy. Tell us about your expertise and let our recruitment team take it from there.</p><div className="actions"><Link className="btn primary" href="/apply">Start your application →</Link><a className="btn ghost" href="#process">See how it works</a></div></div><div className="visual"><div className="card"><h3>Your teaching profile</h3><div className="statrow"><div className="stat"><span>Subjects</span><b>12+</b></div><div className="stat"><span>Formats</span><b>3</b></div><div className="stat"><span>Stages</span><b>4</b></div></div><p style={{color:'#64748b'}}>One professional application. Our team reviews the complete picture.</p></div><div className="float">✓ Secure application<br/><small>Private &amp; protected</small></div></div></div></header>
<section className="section" id="why"><div className="wrap"><div className="center"><h2>A recruitment experience built for professionals</h2><p className="sub">No endless back-and-forth. Give us the information we need once, save your progress, and track your application through a structured process.</p></div><div className="grid3">{benefits.map(x=><div className="feature" key={x[0]}><div className="icon">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
<section className="section" id="process" style={{background:'#f1f5f9'}}><div className="wrap"><div className="center"><h2>From application to classroom</h2><p className="sub">A clear, human recruitment journey designed to respect your time.</p></div><div className="steps">{steps.map((s,i)=><div className="step" key={s}><div className="num">0{i+1}</div><h3>{s}</h3><p className="sub">{i===0?'Create your candidate profile and contact details.':i===1?'Choose subjects, exams, levels and preferred teaching schedule.':i===2?'Provide qualifications, experience and relevant documents.':'Our team reviews your application and may invite you to the next stage.'}</p></div>)}</div></div></section>
<section className="section" id="faq"><div className="wrap"><div className="center"><h2>Questions, answered</h2><p className="sub">You can save your application at any stage and return later.</p></div><div className="grid3"><div className="feature"><h3>Who can apply?</h3><p>Experienced teachers, subject specialists and qualified educators who can demonstrate strong communication and subject knowledge.</p></div><div className="feature"><h3>What documents do I need?</h3><p>Prepare your relevant qualifications and professional documents. The application will guide you through what is required.</p></div><div className="feature"><h3>Can I edit my application?</h3><p>Yes. Draft applications can be resumed before final submission, so you can complete the form at your own pace.</p></div></div></div></section>
<div className="wrap"><section className="cta"><h2>Ready to join Pinnacle?</h2><p>Start your application and show us what makes you an exceptional tutor.</p><Link className="btn primary" href="/apply">Begin application</Link></section></div>
<footer className="footer"><div className="wrap">© 2026 Pinnacle Tutors Academy · Tutor Recruitment</div></footer></>}
