'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase';
const subjects=['Mathematics','English Language','Physics','Chemistry','Biology','Economics','Government','Literature','Computer Science','Further Mathematics'];
const exams=['JAMB / UTME','WAEC / SSCE','NECO','IGCSE','A-Level','BECE'];
const empty={first_name:'',last_name:'',email:'',phone:'',city:'',bio:'',qualifications:'',subjects:[] as string[],exams:[] as string[],experience:'',formats:[] as string[],availability:'',tech:'',screening:''};
export default function ApplyFixed(){const [step,setStep]=useState(1);const [data,setData]=useState<any>(empty);const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [done,setDone]=useState('');
useEffect(()=>{const d=localStorage.getItem('pta-tutor-draft');if(d)try{setData(JSON.parse(d))}catch{}},[]);useEffect(()=>{localStorage.setItem('pta-tutor-draft',JSON.stringify(data))},[data]);
const pct=useMemo(()=>step*20,[step]);
function set(k:string,v:any){setData((d:any)=>({...d,[k]:v}))}function toggle(k:string,v:string){set(k,data[k].includes(v)?data[k].filter((x:string)=>x!==v):[...data[k],v])}
const examWindow=useMemo(()=>{const e=data.exams as string[];const waec=e.includes('WAEC / SSCE'),jamb=e.includes('JAMB / UTME');if(waec&&jamb)return '7:00 AM to 11:00 AM';if(waec)return '7:00 AM to 9:00 AM';if(jamb)return '9:00 AM to 11:00 AM';return ''},[data.exams]);
function next(){if(step===1&&!data.first_name.trim())return alert('Please enter your first name.');if(step===1&&!data.email.includes('@'))return alert('Please enter a valid email.');if(step===2&&!data.exams.length)return alert('Please select at least one exam category.');if(step===4&&examWindow&&!data.availability)return alert('Please tell us whether you can teach within the requested time.');setStep(Math.min(5,step+1))}
async function submit(){setBusy(true);try{const sb=supabase();const {data:app,error}=await sb.rpc('submit_tutor_application',{p_email:data.email.trim().toLowerCase(),p_first_name:data.first_name,p_last_name:data.last_name,p_phone:data.phone,p_city:data.city,p_bio:data.bio,p_qualifications:data.qualifications.split('\\n').filter(Boolean),p_subjects:data.subjects,p_exam_categories:data.exams,p_experience_years:Number(data.experience)||0,p_teaching_formats:data.formats,p_availability:{text:data.availability,teaching_window:examWindow},p_technology:{text:data.tech},p_screening:{text:data.screening}});if(error)throw error;const result=Array.isArray(app)?app[0]:app;if(!result?.reference_no)throw new Error('The application could not be created. Please try again.');const paths:string[]=[];for(const f of files.slice(0,5)){const path=`${result.reference_no}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('tutor-documents').upload(path,f,{upsert:false});if(up.error)throw new Error(`Document upload failed: ${up.error.message}`);paths.push(path)}if(paths.length){const {error:attachError}=await sb.rpc('attach_tutor_documents',{p_reference_no:result.reference_no,p_upload_token:result.upload_token,p_paths:paths});if(attachError)throw attachError}localStorage.removeItem('pta-tutor-draft');setDone(result.reference_no)}catch(e:any){alert(e.message||'Could not submit application. Please try again.')}finally{setBusy(false)}}
if(done)return <main className="formPage"><div className="formShell"><div className="formCard" style={{textAlign:'center',padding:'60px 30px'}}><span className="eyebrow">APPLICATION RECEIVED</span><h1 style={{fontFamily:'Plus Jakarta Sans',fontSize:42}}>You're on your way.</h1><p className="sub">Your application reference number is</p><div style={{fontSize:30,fontWeight:800,margin:'18px 0',letterSpacing:1}}>{done}</div><p className="sub">Keep this reference number for your records. Our recruitment team will review your submission and contact you if you progress to the next stage.</p><Link className="btn primary" href="/">Return home</Link></div></div></main>;
return <main className="formPage"><div className="formShell"><div className="brand"><span className="mark">P</span><span>Pinnacle Tutors Academy</span></div><div className="formCard" style={{marginTop:25}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><span className="eyebrow">TUTOR APPLICATION</span><h1 style={{fontFamily:'Plus Jakarta Sans',marginBottom:0}}>Tell us about you</h1></div><b>Step {step} of 5</b></div><div className="progress"><div style={{width:`${pct}%`}}/></div>
{step===1&&<div className="fields"><div className="field"><label>First name *</label><input value={data.first_name} onChange={e=>set('first_name',e.target.value)}/></div><div className="field"><label>Last name *</label><input value={data.last_name} onChange={e=>set('last_name',e.target.value)}/></div><div className="field"><label>Email *</label><input type="email" value={data.email} onChange={e=>set('email',e.target.value)}/></div><div className="field"><label>Phone *</label><input value={data.phone} onChange={e=>set('phone',e.target.value)}/></div><div className="field full"><label>City / location</label><input value={data.city} onChange={e=>set('city',e.target.value)}/></div><div className="field full"><label>Short professional introduction</label><textarea rows={5} value={data.bio} onChange={e=>set('bio',e.target.value)}/></div></div>}
{step===2&&<><h3>What can you teach?</h3><p className="sub">Select your subjects and exam categories.</p><div className="checkgrid">{subjects.map(x=><label className="check" key={x}><input type="checkbox" checked={data.subjects.includes(x)} onChange={()=>toggle('subjects',x)}/> {x}</label>)}</div><h3 style={{marginTop:28}}>Exam categories *</h3><div className="checkgrid">{exams.map(x=><label className="check" key={x}><input type="checkbox" checked={data.exams.includes(x)} onChange={()=>toggle('exams',x)}/> {x}</label>)}</div></>}
{step===3&&<div className="fields"><div className="field full"><label>Qualifications (one per line)</label><textarea rows={6} placeholder="B.Sc. Mathematics\nPGDE\n..." value={data.qualifications} onChange={e=>set('qualifications',e.target.value)}/></div><div className="field"><label>Years of teaching experience</label><input type="number" min="0" value={data.experience} onChange={e=>set('experience',e.target.value)}/></div><div className="field"><label>Preferred formats</label><select multiple value={data.formats} onChange={e=>set('formats',Array.from(e.target.selectedOptions).map(o=>o.value))}><option>Online</option><option>In-person</option><option>Hybrid</option></select></div><div className="field full"><label>Relevant certificates / documents</label><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small style={{color:'#64748b'}}>Up to 5 files.</small></div></div>}
{step===4&&<div className="fields"><div className="field full"><label>Can you teach within {examWindow||'the required time window'}?</label>{examWindow?<><p className="sub" style={{marginTop:0}}>Based on your exam selection, your teaching window is <strong>{examWindow}</strong>.</p><div className="checkgrid"><label className="check"><input type="radio" name="availability" checked={data.availability==='Yes'} onChange={()=>set('availability','Yes')}/> Yes, I can teach within this time</label><label className="check"><input type="radio" name="availability" checked={data.availability==='No'} onChange={()=>set('availability','No')}/> No, I cannot</label></div></>:<p className="sub">Select WAEC/SSCE or JAMB/UTME in the previous step to see the required window.</p>}</div><div className="field full"><label>Technology &amp; internet readiness</label><textarea rows={5} placeholder="Describe your device, internet reliability and online teaching setup." value={data.tech} onChange={e=>set('tech',e.target.value)}/></div></div>}
{step===5&&<div className="fields"><div className="field full"><label>Screening question</label><textarea rows={8} placeholder="What makes an excellent tutor, and how do you help a struggling student improve?" value={data.screening} onChange={e=>set('screening',e.target.value)}/></div><div className="feature full"><b>Before you submit</b><p className="sub">We securely store your application for recruitment review. Your information is not displayed to other applicants.</p></div></div>}
<div className="formActions">{step>1?<button className="btn ghost" onClick={()=>setStep(step-1)}>Back</button>:<Link className="btn ghost" href="/">Cancel</Link>}{step<5?<button className="btn primary" onClick={next}>Continue →</button>:<button className="btn primary" disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit application'}</button>}</div></div></div></main>}
